### ISSUE TITLE
Principal hierarchy declarations

### ISSUE THREAD

**Issue by MikaelElkiaer** [des105f16/Editor#12]
Syntax:
After declaring principals, it should be possible to declare principal hierarchy relations.
This is done with the following type of statement: `p1 --> p2, p3;`, signifying that principal p1 can act for principals p2 and p3.

As each declared function will have an implicit principal, named the same as the function itself, it should be possible to declare acts-for relations for these as wells.

Semantics:
For each principal, it should contain a list of the principals that it can explicitly act for.
Avoid circular dependencies.

**Comment by deaddog** [comment]
This has a dependency on https://github.com/des105f16/Inference/issues/4

**Comment by MikaelElkiaer** [comment]
Dependent on #15.
